### ISSUE TITLE
MultiQC Error when running pipeline in Ubuntu WSL under win 10

### ISSUE THREAD

**Issue by jkbenotmane** [nf-core/nanoseq#112]
When running the pipeline in a Ubuntu 20.4 wsl 2 with docker windows the pipeline errors out before finishing when creating the MultiQC Report:

Log from Commandline:

jkbenotmane@DESKTOP-H68A51G:/mnt/d/Dropbox/KBJasim/Projects/Capture_Sequencing/Samples/SpaTCR/SPATCR1_2/Nextflow _pipeline$ nextflow run nf-core/nanoseq --input '/mnt/d/Dropbox/KBJasim/Projects/Capture_Sequencing/Samples/SpaTCR/SPATCR1_2/Nextflow _pipeline/SPATCR#1_2_samplesheet_10XVDJ.csv' --protocol cDNA --skip_basecalling --skip_demultiplexing --skip_quantification --outdir '/mnt/d/Dropbox/KBJasim/Projects/Capture_Sequencing/Samples/SpaTCR/SPATCR1_2/Nextflow _pipeline/Merged_SPATCR1_2_10XVDJ' --max_memory '30.GB' --max_cpus 8 -profile docker -w "Output_logs_1"
N E X T F L O W  ~  version 20.10.0
Launching `nf-core/nanoseq` [berserk_tesla] - revision: ad5b2bb7a3 [master]
----------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/nanoseq v1.1.0
----------------------------------------------------
Pipeline Release     : master
Run Name             : berserk_tesla
Samplesheet          : /mnt/d/Dropbox/KBJasim/Projects/Capture_Sequencing/Samples/SpaTCR/SPATCR1_2/Nextflow _pipeline/SPATCR#1_2_samplesheet_10XVDJ.csv
Protocol             : cDNA
Stranded             : No
Skip Basecalling     : Yes
Skip Demultiplexing  : Yes
Aligner              : minimap2
Save Intermeds       : No
Max Resources        : 30.GB memory, 8 cpus, 10d time per job
Container            : docker - nfcore/nanoseq:1.1.0
Output dir           : /mnt/d/Dropbox/KBJasim/Projects/Capture_Sequencing/Samples/SpaTCR/SPATCR1_2/Nextflow _pipeline/Merged_SPATCR1_2_10XVDJ
Launch dir           : /mnt/d/Dropbox/KBJasim/Projects/Capture_Sequencing/Samples/SpaTCR/SPATCR1_2/Nextflow _pipeline
Working dir          : /mnt/d/Dropbox/KBJasim/Projects/Capture_Sequencing/Samples/SpaTCR/SPATCR1_2/Nextflow _pipeline/Output_logs_1
Script dir           : /home/jkbenotmane/.nextflow/assets/nf-core/nanoseq
User                 : jkbenotmane
Config Profile       : docker
Config Files         : /home/jkbenotmane/.nextflow/assets/nf-core/nanoseq/nextflow.config
----------------------------------------------------
executor >  local (13)
[d7/9b11bb] process > CHECK_SAMPLESHEET (SPATCR#1_2_samplesheet_10XVDJ.csv) [100%] 1 of 1 ✔
[-        ] process > PYCOQC                                                -
[-        ] process > NANOPLOT_SUMMARY                                      -
[85/883c8f] process > NANOPLOT_FASTQ (UDI5_R1)                              [100%] 1 of 1 ✔
[dc/6f7c9a] process > FASTQC (UDI5_R1)                                      [100%] 1 of 1 ✔
[f4/ab7749] process > GET_CHROM_SIZES (VDJ_regions.fa)                      [100%] 1 of 1 ✔
[-        ] process > GTF_TO_BED                                            -
[17/4f1020] process > MINIMAP2_INDEX (VDJ_regions.fa)                       [100%] 1 of 1 ✔
[92/867e4c] process > MINIMAP2_ALIGN (UDI5_R1)                              [100%] 1 of 1 ✔
[a6/216f2e] process > SAMTOOLS_SORT (UDI5_R1)                               [100%] 1 of 1 ✔
[7c/297fd3] process > BEDTOOLS_GENOMECOV (UDI5_R1)                          [100%] 1 of 1 ✔
[-        ] process > UCSC_BEDGRAPHTOBIGWIG                                 [  0%] 0 of 1
[24/f45afa] process > BEDTOOLS_BAMTOBED (UDI5_R1)                           [100%] 1 of 1 ✔
[7e/f7a186] process > UCSC_BED12TOBIGBED (UDI5_R1)                          [  0%] 0 of 1
[f9/bbaddf] process > OUTPUT_DOCUMENTATION                                  [100%] 1 of 1 ✔
[75/bb927d] process > GET_SOFTWARE_VERSIONS                                 [100%] 1 of 1 ✔
[a6/d5b1e1] process > MULTIQC (1)                                           [  0%] 0 of 1
Error executing process > 'MULTIQC (1)'

Caused by:
  Process `MULTIQC (1)` terminated with an error exit status (1)

Command executed:

  multiqc . -f

Command exit status:
  1

Command output:
  (empty)

Command error:
  [WARNING]         multiqc : MultiQC Version v1.10.1 now available!
  [INFO   ]         multiqc : This is MultiQC v1.9
  [INFO   ]         multiqc : Template    : default
  [INFO   ]         multiqc : Searching   : /mnt/d/Dropbox/KBJasim/Projects/Capture_Sequencing/Samples/SpaTCR/SPATCR1_2/Nextflow _pipeline/Output_logs_1/a6/d5b1e186c3f88fb02836b305bcea2d
  [INFO   ]         multiqc : Only using modules custom_content, pycoqc, fastqc, samtools, featureCounts
  Matplotlib created a temporary config/cache directory at /tmp/matplotlib-vvr3wxj8 because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
  [INFO   ]  custom_content : nf-core-nanoseq-summary: Found 1 sample (html)
  [INFO   ]  custom_content : software_versions: Found 1 sample (html)
  [INFO   ]          fastqc : Found 1 reports
  /opt/conda/envs/nf-core-nanoseq-1.1.0/lib/python3.8/site-packages/multiqc/plots/bargraph.py:451: UserWarning: FixedFormatter should only be used together with FixedLocator
    axes.set_xticklabels(['{:.0f}%'.format(x) for x in vals])
  /opt/conda/envs/nf-core-nanoseq-1.1.0/lib/python3.8/site-packages/multiqc/plots/bargraph.py:451: UserWarning: FixedFormatter should only be used together with FixedLocator
    axes.set_xticklabels(['{:.0f}%'.format(x) for x in vals])
  [INFO   ]        samtools : Found 1 stats reports
  [INFO   ]        samtools : Found 1 flagstat reports
  [INFO   ]        samtools : Found 1 idxstats reports
  [INFO   ]         multiqc : Compressing plot data
  [INFO   ]         multiqc : Report      : multiqc_report.html
  [INFO   ]         multiqc : Data        : multiqc_data
executor >  local (13)
[d7/9b11bb] process > CHECK_SAMPLESHEET (SPATCR#1_2_samplesheet_10XVDJ.csv) [100%] 1 of 1 ✔
[-        ] process > PYCOQC                                                -
[-        ] process > NANOPLOT_SUMMARY                                      -
[85/883c8f] process > NANOPLOT_FASTQ (UDI5_R1)                              [100%] 1 of 1 ✔
[dc/6f7c9a] process > FASTQC (UDI5_R1)                                      [100%] 1 of 1 ✔
[f4/ab7749] process > GET_CHROM_SIZES (VDJ_regions.fa)                      [100%] 1 of 1 ✔
[-        ] process > GTF_TO_BED                                            -
[17/4f1020] process > MINIMAP2_INDEX (VDJ_regions.fa)                       [100%] 1 of 1 ✔
[92/867e4c] process > MINIMAP2_ALIGN (UDI5_R1)                              [100%] 1 of 1 ✔
[a6/216f2e] process > SAMTOOLS_SORT (UDI5_R1)                               [100%] 1 of 1 ✔
[7c/297fd3] process > BEDTOOLS_GENOMECOV (UDI5_R1)                          [100%] 1 of 1 ✔
[-        ] process > UCSC_BEDGRAPHTOBIGWIG                                 [  0%] 0 of 1
[24/f45afa] process > BEDTOOLS_BAMTOBED (UDI5_R1)                           [100%] 1 of 1 ✔
[7e/f7a186] process > UCSC_BED12TOBIGBED (UDI5_R1)                          [  0%] 0 of 1
[f9/bbaddf] process > OUTPUT_DOCUMENTATION                                  [100%] 1 of 1 ✔
[75/bb927d] process > GET_SOFTWARE_VERSIONS                                 [100%] 1 of 1 ✔
[a6/d5b1e1] process > MULTIQC (1)                                           [100%] 1 of 1, failed: 1 ✘
Execution cancelled -- Finishing pending tasks before exit
Error executing process > 'MULTIQC (1)'

Caused by:
  Process `MULTIQC (1)` terminated with an error exit status (1)

Command executed:

  multiqc . -f

Command exit status:
  1

Command output:
  (empty)

Command error:
  [WARNING]         multiqc : MultiQC Version v1.10.1 now available!
  [INFO   ]         multiqc : This is MultiQC v1.9
  [INFO   ]         multiqc : Template    : default
  [INFO   ]         multiqc : Searching   : /mnt/d/Dropbox/KBJasim/Projects/Capture_Sequencing/Samples/SpaTCR/SPATCR1_2/Nextflow _pipeline/Output_logs_1/a6/d5b1e186c3f88fb02836b305bcea2d
  [INFO   ]         multiqc : Only using modules custom_content, pycoqc, fastqc, samtools, featureCounts
  Matplotlib created a temporary config/cache directory at /tmp/matplotlib-vvr3wxj8 because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
  [INFO   ]  custom_content : nf-core-nanoseq-summary: Found 1 sample (html)
  [INFO   ]  custom_content : software_versions: Found 1 sample (html)
  [INFO   ]          fastqc : Found 1 reports
  /opt/conda/envs/nf-core-nanoseq-1.1.0/lib/python3.8/site-packages/multiqc/plots/bargraph.py:451: UserWarning: FixedFormatter should only be used together with FixedLocator
    axes.set_xticklabels(['{:.0f}%'.format(x) for x in vals])
  /opt/conda/envs/nf-core-nanoseq-1.1.0/lib/python3.8/site-packages/multiqc/plots/bargraph.py:451: UserWarning: FixedFormatter should only be used together with FixedLocator
    axes.set_xticklabels(['{:.0f}%'.format(x) for x in vals])
  [INFO   ]        samtools : Found 1 stats reports
  [INFO   ]        samtools : Found 1 flagstat reports
  [INFO   ]        samtools : Found 1 idxstats reports
  [INFO   ]         multiqc : Compressing plot data
  [INFO   ]         multiqc : Report      : multiqc_report.html
  [INFO   ]         multiqc : Data        : multiqc_data
executor >  local (13)
[d7/9b11bb] process > CHECK_SAMPLESHEET (SPATCR#1_2_samplesheet_10XVDJ.csv) [100%] 1 of 1 ✔
[-        ] process > PYCOQC                                                -
[-        ] process > NANOPLOT_SUMMARY                                      -
[85/883c8f] process > NANOPLOT_FASTQ (UDI5_R1)                              [100%] 1 of 1 ✔
[dc/6f7c9a] process > FASTQC (UDI5_R1)                                      [100%] 1 of 1 ✔
[f4/ab7749] process > GET_CHROM_SIZES (VDJ_regions.fa)                      [100%] 1 of 1 ✔
[-        ] process > GTF_TO_BED                                            -
[17/4f1020] process > MINIMAP2_INDEX (VDJ_regions.fa)                       [100%] 1 of 1 ✔
[92/867e4c] process > MINIMAP2_ALIGN (UDI5_R1)                              [100%] 1 of 1 ✔
[a6/216f2e] process > SAMTOOLS_SORT (UDI5_R1)                               [100%] 1 of 1 ✔
[7c/297fd3] process > BEDTOOLS_GENOMECOV (UDI5_R1)                          [100%] 1 of 1 ✔
[-        ] process > UCSC_BEDGRAPHTOBIGWIG                                 [  0%] 0 of 1
[24/f45afa] process > BEDTOOLS_BAMTOBED (UDI5_R1)                           [100%] 1 of 1 ✔
[7e/f7a186] process > UCSC_BED12TOBIGBED (UDI5_R1)                          [100%] 1 of 1 ✔
[f9/bbaddf] process > OUTPUT_DOCUMENTATION                                  [100%] 1 of 1 ✔
[75/bb927d] process > GET_SOFTWARE_VERSIONS                                 [100%] 1 of 1 ✔
[a6/d5b1e1] process > MULTIQC (1)                                           [100%] 1 of 1, failed: 1 ✘
Execution cancelled -- Finishing pending tasks before exit
Error executing process > 'MULTIQC (1)'

Caused by:
  Process `MULTIQC (1)` terminated with an error exit status (1)

Command executed:

  multiqc . -f

Command exit status:
  1

Command output:
  (empty)

Command error:
  [WARNING]         multiqc : MultiQC Version v1.10.1 now available!
  [INFO   ]         multiqc : This is MultiQC v1.9
  [INFO   ]         multiqc : Template    : default
  [INFO   ]         multiqc : Searching   : /mnt/d/Dropbox/KBJasim/Projects/Capture_Sequencing/Samples/SpaTCR/SPATCR1_2/Nextflow _pipeline/Output_logs_1/a6/d5b1e186c3f88fb02836b305bcea2d
  [INFO   ]         multiqc : Only using modules custom_content, pycoqc, fastqc, samtools, featureCounts
  Matplotlib created a temporary config/cache directory at /tmp/matplotlib-vvr3wxj8 because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
  [INFO   ]  custom_content : nf-core-nanoseq-summary: Found 1 sample (html)
  [INFO   ]  custom_content : software_versions: Found 1 sample (html)
  [INFO   ]          fastqc : Found 1 reports
  /opt/conda/envs/nf-core-nanoseq-1.1.0/lib/python3.8/site-packages/multiqc/plots/bargraph.py:451: UserWarning: FixedFormatter should only be used together with FixedLocator
    axes.set_xticklabels(['{:.0f}%'.format(x) for x in vals])
  /opt/conda/envs/nf-core-nanoseq-1.1.0/lib/python3.8/site-packages/multiqc/plots/bargraph.py:451: UserWarning: FixedFormatter should only be used together with FixedLocator
    axes.set_xticklabels(['{:.0f}%'.format(x) for x in vals])
  [INFO   ]        samtools : Found 1 stats reports
  [INFO   ]        samtools : Found 1 flagstat reports
  [INFO   ]        samtools : Found 1 idxstats reports
  [INFO   ]         multiqc : Compressing plot data
  [INFO   ]         multiqc : Report      : multiqc_report.html
  [INFO   ]         multiqc : Data        : multiqc_data
  Traceback (most recent call last):
    File "/opt/conda/envs/nf-core-nanoseq-1.1.0/bin/multiqc", line 6, in <module>
executor >  local (13)
[d7/9b11bb] process > CHECK_SAMPLESHEET (SPATCR#1_2_samplesheet_10XVDJ.csv) [100%] 1 of 1 ✔
[-        ] process > PYCOQC                                                -
[-        ] process > NANOPLOT_SUMMARY                                      -
[85/883c8f] process > NANOPLOT_FASTQ (UDI5_R1)                              [100%] 1 of 1 ✔
[dc/6f7c9a] process > FASTQC (UDI5_R1)                                      [100%] 1 of 1 ✔
[f4/ab7749] process > GET_CHROM_SIZES (VDJ_regions.fa)                      [100%] 1 of 1 ✔
[-        ] process > GTF_TO_BED                                            -
[17/4f1020] process > MINIMAP2_INDEX (VDJ_regions.fa)                       [100%] 1 of 1 ✔
[92/867e4c] process > MINIMAP2_ALIGN (UDI5_R1)                              [100%] 1 of 1 ✔
[a6/216f2e] process > SAMTOOLS_SORT (UDI5_R1)                               [100%] 1 of 1 ✔
[7c/297fd3] process > BEDTOOLS_GENOMECOV (UDI5_R1)                          [100%] 1 of 1 ✔
[-        ] process > UCSC_BEDGRAPHTOBIGWIG                                 [  0%] 0 of 1
[24/f45afa] process > BEDTOOLS_BAMTOBED (UDI5_R1)                           [100%] 1 of 1 ✔
[7e/f7a186] process > UCSC_BED12TOBIGBED (UDI5_R1)                          [100%] 1 of 1 ✔
[f9/bbaddf] process > OUTPUT_DOCUMENTATION                                  [100%] 1 of 1 ✔
[75/bb927d] process > GET_SOFTWARE_VERSIONS                                 [100%] 1 of 1 ✔
[a6/d5b1e1] process > MULTIQC (1)                                           [100%] 1 of 1, failed: 1 ✘

Error executing process > 'MULTIQC (1)'

Caused by:
  Process `MULTIQC (1)` terminated with an error exit status (1)

Command executed:

  multiqc . -f

Command exit status:
  1

Command output:
  (empty)

Command error:
  [WARNING]         multiqc : MultiQC Version v1.10.1 now available!
  [INFO   ]         multiqc : This is MultiQC v1.9
  [INFO   ]         multiqc : Template    : default
  [INFO   ]         multiqc : Searching   : /mnt/d/Dropbox/KBJasim/Projects/Capture_Sequencing/Samples/SpaTCR/SPATCR1_2/Nextflow _pipeline/Output_logs_1/a6/d5b1e186c3f88fb02836b305bcea2d
  [INFO   ]         multiqc : Only using modules custom_content, pycoqc, fastqc, samtools, featureCounts
  Matplotlib created a temporary config/cache directory at /tmp/matplotlib-vvr3wxj8 because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
  [INFO   ]  custom_content : nf-core-nanoseq-summary: Found 1 sample (html)
  [INFO   ]  custom_content : software_versions: Found 1 sample (html)
  [INFO   ]          fastqc : Found 1 reports
  /opt/conda/envs/nf-core-nanoseq-1.1.0/lib/python3.8/site-packages/multiqc/plots/bargraph.py:451: UserWarning: FixedFormatter should only be used together with FixedLocator
    axes.set_xticklabels(['{:.0f}%'.format(x) for x in vals])
  /opt/conda/envs/nf-core-nanoseq-1.1.0/lib/python3.8/site-packages/multiqc/plots/bargraph.py:451: UserWarning: FixedFormatter should only be used together with FixedLocator
    axes.set_xticklabels(['{:.0f}%'.format(x) for x in vals])
  [INFO   ]        samtools : Found 1 stats reports
  [INFO   ]        samtools : Found 1 flagstat reports
  [INFO   ]        samtools : Found 1 idxstats reports
  [INFO   ]         multiqc : Compressing plot data
  [INFO   ]         multiqc : Report      : multiqc_report.html
  [INFO   ]         multiqc : Data        : multiqc_data
  Traceback (most recent call last):
    File "/opt/conda/envs/nf-core-nanoseq-1.1.0/bin/multiqc", line 6, in <module>
      from multiqc.__main__ import multiqc
    File "/opt/conda/envs/nf-core-nanoseq-1.1.0/lib/python3.8/site-packages/multiqc/__main__.py", line 44, in <module>
      multiqc.run_cli(prog_name='multiqc')
    File "/opt/conda/envs/nf-core-nanoseq-1.1.0/lib/python3.8/site-packages/click/core.py", line 829, in __call__
      return self.main(*args, **kwargs)
    File "/opt/conda/envs/nf-core-nanoseq-1.1.0/lib/python3.8/site-packages/click/core.py", line 782, in main
      rv = self.invoke(ctx)
    File "/opt/conda/envs/nf-core-nanoseq-1.1.0/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/opt/conda/envs/nf-core-nanoseq-1.1.0/lib/python3.8/site-packages/click/core.py", line 610, in invoke
      return callback(*args, **kwargs)
    File "/opt/conda/envs/nf-core-nanoseq-1.1.0/lib/python3.8/site-packages/multiqc/multiqc.py", line 215, in run_cli
      multiqc_run = run(
    File "/opt/conda/envs/nf-core-nanoseq-1.1.0/lib/python3.8/site-packages/multiqc/multiqc.py", line 784, in run
      copy_tree(config.data_tmp_dir, config.data_dir)
    File "/opt/conda/envs/nf-core-nanoseq-1.1.0/lib/python3.8/distutils/dir_util.py", line 161, in copy_tree
      copy_file(src_name, dst_name, preserve_mode,
    File "/opt/conda/envs/nf-core-nanoseq-1.1.0/lib/python3.8/distutils/file_util.py", line 158, in copy_file
      os.utime(dst, (st[ST_ATIME], st[ST_MTIME]))
  PermissionError: [Errno 1] Operation not permitted

Work dir:
  /mnt/d/Dropbox/KBJasim/Projects/Capture_Sequencing/Samples/SpaTCR/SPATCR1_2/Nextflow _pipeline/Output_logs_1/a6/d5b1e186c3f88fb02836b305bcea2d

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

**Comment by jkbenotmane** [comment]
**SOLVED:**

**Perform Pipeline as sudo** (on mounted drive of wsl instance.)

root@DESKTOP-H68A51G:/mnt/c/Users/jkben/OneDrive/Desktop/SPATCR1_2_nextflow_output# nextflow run nf-core/nanoseq --input 'SPATCR#1_2_samplesheet_10XVDJ_all_trimmed.csv' --protocol cDNA --skip_basecalling --skip_demultiplexing --skip_quantification --outdir 'Output' --max_memory '30.GB' --max_cpus 8 -profile docker
N E X T F L O W  ~  version 20.10.0
Launching `nf-core/nanoseq` [awesome_bhabha] - revision: ad5b2bb7a3 [master]
----------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/nanoseq v1.1.0
----------------------------------------------------
Pipeline Release     : master
Run Name             : awesome_bhabha
Samplesheet          : SPATCR#1_2_samplesheet_10XVDJ_all_trimmed.csv
Protocol             : cDNA
Stranded             : No
Skip Basecalling     : Yes
Skip Demultiplexing  : Yes
Aligner              : minimap2
Save Intermeds       : No
Max Resources        : 30.GB memory, 8 cpus, 10d time per job
Container            : docker - nfcore/nanoseq:1.1.0
Output dir           : Output
Launch dir           : /mnt/c/Users/jkben/OneDrive/Desktop/SPATCR1_2_nextflow_output
Working dir          : /mnt/c/Users/jkben/OneDrive/Desktop/SPATCR1_2_nextflow_output/work
Script dir           : /root/.nextflow/assets/nf-core/nanoseq
User                 : root
Config Profile       : docker
Config Files         : /root/.nextflow/assets/nf-core/nanoseq/nextflow.config
----------------------------------------------------
executor >  local (14)
[6b/9b7c1c] process > CHECK_SAMPLESHEET (SPATCR#1_2_samplesheet_10XVDJ_all_trimmed.csv) [100%] 1 of 1 ✔
[-        ] process > PYCOQC                                                            -
[-        ] process > NANOPLOT_SUMMARY                                                  -
[cf/07a7c8] process > NANOPLOT_FASTQ (UDI5_R1)                                          [100%] 1 of 1 ✔
[2e/78c2ba] process > FASTQC (UDI5_R1)                                                  [100%] 1 of 1 ✔
[e9/bb81ee] process > GET_CHROM_SIZES (VDJ_regions.fa)                                  [100%] 1 of 1 ✔
[-        ] process > GTF_TO_BED                                                        -
[19/66e268] process > MINIMAP2_INDEX (VDJ_regions.fa)                                   [100%] 1 of 1 ✔
[2c/d18ce4] process > MINIMAP2_ALIGN (UDI5_R1)                                          [100%] 1 of 1 ✔
[9a/de0916] process > SAMTOOLS_SORT (UDI5_R1)                                           [100%] 1 of 1 ✔
[b8/926cd2] process > BEDTOOLS_GENOMECOV (UDI5_R1)                                      [100%] 1 of 1 ✔
[31/ae95c9] process > UCSC_BEDGRAPHTOBIGWIG (UDI5_R1)                                   [100%] 1 of 1 ✔
[0e/4c821b] process > BEDTOOLS_BAMTOBED (UDI5_R1)                                       [100%] 1 of 1 ✔
[e1/8c61a2] process > UCSC_BED12TOBIGBED (UDI5_R1)                                      [100%] 1 of 1 ✔
[db/1ae986] process > OUTPUT_DOCUMENTATION                                              [100%] 1 of 1 ✔
[13/3c996a] process > GET_SOFTWARE_VERSIONS                                             [100%] 1 of 1 ✔
[df/bb46bd] process > MULTIQC (1)                                                       [100%] 1 of 1 ✔
-[nf-core/nanoseq] Pipeline completed successfully-
Completed at: 21-Apr-2021 22:08:22
Duration    : 14m 59s
CPU hours   : 1.3
Succeeded   : 14
