### ISSUE TITLE
ascii codec issue

### ISSUE THREAD

**Issue by Bruce-BC** [nf-core/nanoseq#67]
Dear nf-core team,

Hello guys.
2 weeks ago, the moment that I found nextflow and nf-core library, I was so happy that I could re-write all pipelines I've tried on you guy's platform.
by the way, in the period testing newly written pipelines, I found some errors below.

$ nf-core lint --release .

                                          ,--./,-.
          ___     __   __   __   ___     /,-._.--~\
    |\ | |__  __ /  ` /  \ |__) |__         }  {
    | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                          `._,._,'

Running pipeline tests  [####################################]  100%  None
Traceback (most recent call last):
  File "/home/Program/miniconda3/bin/nf-core", line 353, in <module>
    nf_core_cli()
  File "/home/Program/miniconda3/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/Program/miniconda3/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/Program/miniconda3/lib/python2.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/Program/miniconda3/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/Program/miniconda3/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/Program/miniconda3/bin/nf-core", line 239, in lint
    lint_obj = nf_core.lint.run_linting(pipeline_dir, release)
  File "/home/Program/miniconda3/lib/python2.7/site-packages/nf_core/lint.py", line 54, in run_linting
    lint_obj.print_results()
  File "/home/Program/miniconda3/lib/python2.7/site-packages/nf_core/lint.py", line 922, in print_results
    click.style("  [{}] {:>4} tests failed".format(u'\u2717', len(self.failed)), fg='red') + rl
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2714' in position 0: ordinal not in range(128)

Only things that I found issue is that it seems kind of type-casting error, but nothing else.
Please let me know how to lint properly and run system as you've intended.

Thanks.

**Comment by drpatelh** [comment]
Hi @Bruce-BC! It appears I wasn't watching this repo at the time so I missed this issue. Sorry. I am not completely sure what you are trying to do above? That particular command is to lint the pipeline code before we release to check for consistency with the nf-core/tools pipeline template. 

Will close for now but let me know if I misunderstood something. Thanks!
