### ISSUE TITLE
NanoPlot 1.28.4 has crashed

### ISSUE THREAD

**Issue by mlorthiois** [nf-core/nanoseq#75]
Hi,
I encounter a problem when using Nanoseq with the singularity profile.

Here are my commands:
```
nextflow run nf-core/nanoseq -latest \
    --input /home/genouest/cnrs_umr6290/mlorthiois/nanoseq_test/input.csv \
    --protocol cDNA \
    --input_path /home/genouest/cnrs_umr6290/mlorthiois/nanoseq_test/data \
    --flowcell FLO-MIN106 \
    --kit SQK-DCS109 \
    --skip_demultiplexing \
    -profile singularity
```

During the Nanoplot step, I get this error :

```
Error executing process > 'NanoPlotSummary (sequencing_summary.txt)'

Caused by:
  Process `NanoPlotSummary (sequencing_summary.txt)` terminated with an error exit status (1)

Command executed:

  NanoPlot -t 2 --summary sequencing_summary.txt

Command exit status:
  1

Command output:

  If you read this then NanoPlot 1.28.4 has crashed :-(
  Please try updating NanoPlot and see if that helps...
  
  If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
  If you could include the log file that would be really helpful.
  Thanks!
  
Command error:
  Traceback (most recent call last):
    File "/opt/conda/envs/nf-core-nanoseq-1.0.0/bin/NanoPlot", line 10, in <module>
      sys.exit(main())
    File "/opt/conda/envs/nf-core-nanoseq-1.0.0/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 96, in main
      plots = make_plots(datadf, settings)
    File "/opt/conda/envs/nf-core-nanoseq-1.0.0/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 197, in make_plots
      plot_settings=plot_settings)
    File "/opt/conda/envs/nf-core-nanoseq-1.0.0/lib/python3.7/site-packages/nanoplotter/timeplots.py", line 46, in time_plots
      color=color)
    File "/opt/conda/envs/nf-core-nanoseq-1.0.0/lib/python3.7/site-packages/nanoplotter/timeplots.py", line 238, in cumulative_yield
      scatter_kws={"s": 3})
    File "/opt/conda/envs/nf-core-nanoseq-1.0.0/lib/python3.7/site-packages/seaborn/regression.py", line 810, in regplot
      x_jitter, y_jitter, color, label)
    File "/opt/conda/envs/nf-core-nanoseq-1.0.0/lib/python3.7/site-packages/seaborn/regression.py", line 114, in __init__
      self.dropna("x", "y", "units", "x_partial", "y_partial")
    File "/opt/conda/envs/nf-core-nanoseq-1.0.0/lib/python3.7/site-packages/seaborn/regression.py", line 66, in dropna
      setattr(self, var, val[not_na])
  IndexError: invalid index to scalar variable.
```

This error is reported on this [issue](https://github.com/wdecoster/NanoPlot/issues/187). This one recommends to update Seaborn to version 0.10.1. 

Will updating seaborn be enough to fix my error? If so, how can I modify the Singularity container to include the new version of Seaborn?

Thanks.

**Comment by drpatelh** [comment]
Hi @mlorthiois ! Apologies for taking so long to respond. I wasn't watching this repo for some reason. That is indeed an issue and has now been fixed on the [`dev`](https://github.com/nf-core/nanoseq/pull/79/files#diff-9efd195f4e9bfb79ccd456a1d8370fafcc4bcb0b00ea3799222667d2ae818533) branch. We should be releasing soon so things will be working again.
